[package]
name = "broke-amusement-server"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["blocking"] }
serde_json = "1.0.140"
winapi = { version = "0.3", features = ["winuser", "tlhelp32", "processthreadsapi", "handleapi", "winnt", "psapi"] }
